import { makeEnum } from '@transcend-io/type-utils';

// adapted from https://gist.github.com/Josantonius/b455e315bc7f790d14b136d61d9ae469
export const BrowserLanguage = makeEnum({
  '(Afan)/Oromoor/Oriya': 'om',
  Abkhazian: 'ab',
  Afar: 'aa',
  Afrikaans: 'af',
  Akan: 'ak',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  'Arabic (Algeria)': 'ar-DZ',
  'Arabic (Bahrain)': 'ar-BH',
  'Arabic (Egypt)': 'ar-EG',
  'Arabic (Iraq)': 'ar-IQ',
  'Arabic (Jordan)': 'ar-JO',
  'Arabic (Kuwait)': 'ar-KW',
  'Arabic (Lebanon)': 'ar-LB',
  'Arabic (Morocco)': 'ar-MA',
  'Arabic (Oman)': 'ar-OM',
  'Arabic (Qatar)': 'ar-QA',
  'Arabic (Saudi Arabia)': 'ar-SA',
  'Arabic (Syria)': 'ar-SY',
  'Arabic (Tunisia)': 'ar-TN',
  'Arabic (U.A.E.)': 'ar-AE',
  'Arabic (Yemen)': 'ar-YE',
  'Arabic (libya)': 'ar-LY',
  Aragonese: 'an',
  Armenian: 'hy',
  Assamese: 'as',
  Avaric: 'av',
  Avestan: 'ae',
  Aymara: 'ay',
  Azeri: 'az',
  Bambara: 'bm',
  Bashkir: 'ba',
  Basque: 'eu',
  Belarusian: 'be',
  Bengali: 'bn',
  Bhutani: 'dz',
  Bihari: 'bh',
  Bislama: 'bi',
  Bosnian: 'bs',
  Breton: 'br',
  'Bulgarian (Bulgaria)': 'bg-BG',
  Bulgarian: 'bg',
  Burmese: 'my',
  Cambodian: 'km',
  Catalan: 'ca',
  Chamorro: 'ch',
  Chechen: 'ce',
  Chinese: 'zh',
  'Chinese (China)': 'zh-CN',
  'Chinese (Hong Kong SAR)': 'zh-HK',
  'Chinese (Macau SAR)': 'zh-MO',
  'Chinese (Singapore)': 'zh-SG',
  'Chinese (Simplified)': 'zh-Hans',
  'Chinese (Taiwan)': 'zh-TW',
  Chichewa: 'ny',
  'Church Slavonic': 'cu',
  Cornish: 'kw',
  Corsican: 'co',
  Cree: 'cr',
  'Croatian (Bosnia and Herzegovina)': 'hr-BA',
  'Croatian (Croatia)': 'hr-HR',
  Croatian: 'hr',
  'Czech (Czech Republic)': 'cs-CZ',
  Czech: 'cs',
  Danish: 'da',
  'Danish (Denmark)': 'da-DK',
  Divehi: 'div',
  DivehiDv: 'dv',
  Dutch: 'nl',
  'Dutch (Belgium)': 'nl-BE',
  'Dutch (Netherlands)': 'nl-NL',
  English: 'us',
  'English (Australia)': 'en-AU',
  'English (Belize)': 'en-BZ',
  'English (Canada)': 'en-CA',
  'English (Caribbean)': 'en-CB',
  'English (Ireland)': 'en-IE',
  'English (Jamaica)': 'en-JM',
  'English (New Zealand)': 'en-NZ',
  'English (Philippines)': 'en-PH',
  'English (South Africa)': 'en-ZA',
  'English (Switzerland)': 'en-CH',
  'English (Trinidad)': 'en-TT',
  'English (United Kingdom)': 'en-GB',
  'English (United States)': 'en-US',
  'English (Zimbabwe)': 'en-ZW',
  Esperanto: 'eo',
  Estonian: 'et',
  'Estonian (Estonia)': 'et-EE',
  Ewe: 'ee',
  Faeroese: 'fo',
  Farsi: 'fa',
  Fiji: 'fj',
  Finnish: 'fi',
  'Finnish (Finland)': 'fi-FI',
  French: 'fr',
  'French (Belgium)': 'fr-BE',
  'French (Canada)': 'fr-CA',
  'French (France)': 'fr-FR',
  'French (Luxembourg)': 'fr-LU',
  'French (Monaco)': 'fr-MC',
  'French (Switzerland)': 'fr-CH',
  Frisian: 'fy',
  'FYRO Macedonian': 'mk',
  Gaelic: 'gd',
  Galician: 'gl',
  Ganda: 'lg',
  Georgian: 'ka',
  German: 'de',
  'German (Austria)': 'de-AT',
  'German (Germany)': 'de-DE',
  'German (Liechtenstein)': 'de-LI',
  'German (Luxembourg)': 'de-LU',
  'German (Switzerland)': 'de-CH',
  Greek: 'el',
  'Greek (Greece)': 'el-GR',
  Greenlandic: 'kl',
  Guarani: 'gn',
  Gujarati: 'gu',
  Haitian: 'ht',
  Hausa: 'ha',
  Hebrew: 'iw',
  'Hebrew (Israel)': 'he-IL',
  'Hebrew (Modern)': 'he',
  Herero: 'hz',
  Hindi: 'hi',
  'Hiri Motu': 'ho',
  Hungarian: 'hu',
  'Hungarian (Hungary)': 'hu-HU',
  Icelandic: 'is',
  'Icelandic (Iceland)': 'is-IS',
  Igbo: 'ig',
  Ido: 'io',
  Indonesian: 'in',
  'Indonesian (Modern)': 'id',
  Interlingua: 'ia',
  Interlingue: 'ie',
  Inuktitut: 'iu',
  Inupiak: 'ik',
  Irish: 'ga',
  'Irish (Ireland)': 'ga-IE',
  Italian: 'it',
  'Italian (Italy)': 'it-IT',
  'Italian (Switzerland)': 'it-CH',
  Japanese: 'ja',
  Javanese: 'jw',
  Kannada: 'kn',
  Kanuri: 'kr',
  Kashmiri: 'ks',
  Kazakh: 'kk',
  Kikuyu: 'ki',
  Kinyarwanda: 'rw',
  Kirghiz: 'ky',
  Kirundi: 'rn',
  Kongo: 'kg',
  Konkani: 'kok',
  Korean: 'ko',
  Komi: 'kv',
  Kuanyama: 'kj',
  Kurdish: 'ku',
  Kyrgyz: 'kz',
  Laothian: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  'Latvian (Latvia)': 'lv-LV',
  Limburgan: 'li',
  Lingala: 'ln',
  'Lithuanian (Lithuania)': 'lt-LT',
  Lithuanian: 'lt',
  'Luba-Katanga': 'lu',
  Luxembourgish: 'lb',
  Malagasy: 'mg',
  Malay: 'ms',
  'Malay (Brunei Darussalam)': 'ms-BN',
  'Malay (Malaysia)': 'ms-MY',
  Malayalam: 'ml',
  Maltese: 'mt',
  'Maltese (Malta)': 'mt-MT',
  Manx: 'gv',
  Maori: 'mi',
  Marathi: 'mr',
  Marshallese: 'mh',
  Moldavian: 'mo',
  Mongolian: 'mn',
  Nauru: 'na',
  Navajo: 'nv',
  Ndonga: 'ng',
  'Nepali (India)': 'ne',
  'North Ndebele': 'nd',
  'Northern Sotho': 'ns',
  Norwegian: 'no',
  'Norwegian (Norway)': 'no-NO',
  'Norwegian Bokmål': 'nb',
  'Norwegian Bokmål (Norway)': 'nb-NO',
  'Norwegian Nynorsk': 'nn',
  'Norwegian Nynorsk (Norway)': 'nn-NO',
  'South Ndebele': 'nr',
  Occitan: 'oc',
  Ojibwa: 'oj',
  Oriya: 'or',
  Ossetian: 'os',
  Pali: 'pi',
  'Pashto/Pushto': 'ps',
  Polish: 'pl',
  'Polish (Poland)': 'pl-PL',
  Portuguese: 'pt',
  'Portuguese (Brazil)': 'pt-BR',
  'Portuguese (Portugal)': 'pt-PT',
  'Portuguese (Switzerland)': 'pt-CH',
  Punjabi: 'pa',
  Quechua: 'qu',
  'Quechua (Bolivia)': 'qu-BO',
  'Quechua (Ecuador)': 'qu-EC',
  'Quechua (Peru)': 'qu-PE',
  'Rhaeto-Romanic': 'rm',
  Romanian: 'ro',
  'Romanian (Moldova)': 'ro-MD',
  'Romanian (Romania)': 'ro-RO',
  Russian: 'ru',
  'Russian (Moldova)': 'ru-MD',
  Sami: 'se',
  'Sami (Finland)': 'se-FI',
  'Sami (Norway)': 'se-NO',
  'Sami (Sweden)': 'se-SE',
  Samoan: 'sm',
  Sango: 'sg',
  Sanskrit: 'sa',
  Sardinian: 'sc',
  Serbian: 'sr',
  'Serbian (Bosnia and Herzegovina)': 'sr-BA',
  'Serbian (Serbia and Montenegro)': 'sr-SP',
  'Serbo-Croatian': 'sh',
  Sesotho: 'st',
  Shona: 'sn',
  'Sichuan Yi': 'ii',
  Sindhi: 'sd',
  Singhalese: 'si',
  Siswati: 'ss',
  Slovak: 'sk',
  'Slovak (Slovakia)': 'sk-SK',
  Slovenian: 'sl',
  'Slovenian (Slovenia)': 'sl-SI',
  Somali: 'so',
  Sorbian: 'sb',
  Spanish: 'es',
  'Spanish (Argentina)': 'es-AR',
  'Spanish (Bolivia)': 'es-BO',
  'Spanish (Chile)': 'es-CL',
  'Spanish (Colombia)': 'es-CO',
  'Spanish (Costa Rica)': 'es-CR',
  'Spanish (Dominican Republic)': 'es-DO',
  'Spanish (Ecuador)': 'es-EC',
  'Spanish (El Salvador)': 'es-SV',
  'Spanish (Espa\u00f1a)': 'es-ES',
  'Spanish (Guatemala)': 'es-GT',
  'Spanish (Honduras)': 'es-HN',
  'Spanish (Mexico)': 'es-MX',
  'Spanish (Nicaragua)': 'es-NI',
  'Spanish (Panama)': 'es-PA',
  'Spanish (Paraguay)': 'es-PY',
  'Spanish (Peru)': 'es-PE',
  'Spanish (Puerto Rico)': 'es-PR',
  'Spanish (United States)': 'es-US',
  'Spanish (Uruguay)': 'es-UY',
  'Spanish (Venezuela)': 'es-VE',
  Sundanese: 'su',
  Sutu: 'sx',
  Swahili: 'sw',
  Swedish: 'sv',
  'Swedish (Finland)': 'sv-FI',
  'Swedish (Sweden)': 'sv-SE',
  'Swiss German': 'gsw',
  'Swiss German (Liechtenstein)': 'gsw-LI',
  'Swiss German (Switzerland)': 'gsw-CH',
  Syriac: 'syr',
  Tagalog: 'tl',
  Tahitian: 'ty',
  Tajik: 'tg',
  Tamil: 'ta',
  Tatar: 'tt',
  Telugu: 'te',
  Thai: 'th',
  Tibetan: 'bo',
  Tigrinya: 'ti',
  Tonga: 'to',
  Tsonga: 'ts',
  Tswana: 'tn',
  Turkish: 'tr',
  Turkmen: 'tk',
  Twi: 'tw',
  Uighur: 'ug',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Venda: 've',
  Vietnamese: 'vi',
  Volapuk: 'vo',
  Walloon: 'wa',
  Welsh: 'cy',
  Wolof: 'wo',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zhuang: 'za',
  Zulu: 'zu',
});

/** Overrides type */
export type BrowserLanguage =
  (typeof BrowserLanguage)[keyof typeof BrowserLanguage];
