name: npm_deprecate
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string
      message:
        description: 'message'
        required: true
        type: string

jobs:
  npm-deprecate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          yarn npm deprecate "${PACKAGE_NAME}@${{ inputs.version }}" "${{ inputs.message }}"
